name: BGE Model Docker Image Actions
on:
  push:
    branches:
      - feature-actions

jobs:

  base_job:
    name: Base Image Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Basic Image
        run: make build SDK_VERSION=0.1.1 ENVIRONMENT=basic

      - name: Build Build Image
        run: make build SDK_VERSION=0.1.1 ENVIRONMENT=build
