name: BGE Model Docker Image Actions
on:
  push:
    tags:
      - 'v*'

jobs:

  base_job:
    name: Base Image Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

      # - name: Create Basic Image
      #   run: make build SDK_VERSION=0.1.1 ENVIRONMENT=basic

      # - name: Create Build Image
      #   run: make build SDK_VERSION=0.1.1 ENVIRONMENT=build

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v1.10.0
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push Basic Docker Image
      #   run: make push SDK_VERSION=0.1.1 ENVIRONMENT=basic

      # - name: Push Build Docker Image
      #   run: make push SDK_VERSION=0.1.1 ENVIRONMENT=build
