name: BGE Model Docker Image Actions
on:
  push:
    branches:
      - feature-actions

jobs:

  base_job:
    name: Create Base Image
    runs-on: ubuntu-18.04
    steps:
      - run: echo "base"

  build_job:
    name: Create Build Image
    runs-on: ubuntu-18.04
    needs: base_job
    steps:
      - run: echo "build"